Repository falcosecurity/falcosidekick-ui, pull requests merged in 2021-03, with the labels that each got.

#21 allow to filter by clicking on any badge
  static/index.html
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#22 add goreleaser
  .circleci/config.yml
  .goreleaser.yml
Labels: approved, area/build, dco-signoff: yes, kind/feature, lgtm, size/M

#24 go: update to use go1.16.x
  .circleci/config.yml
  Dockerfile
  go.mod
  go.sum
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS

#25 image: update alpine to use tag 1.13
  Dockerfile
Labels: approved, dco-signoff: yes, kind/cleanup, kind/feature, lgtm, size/XS
