Repository falcosecurity/falcosidekick-ui, pull requests merged in 2021-02, with the labels that each got.

#8 new(.github): add pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#12 update readme with badges and details
  README.md
Labels: approved, area/build, dco-signoff: yes, kind/documentation, lgtm, size/M

#14 fix(docs): corrected run with docker command at README
  README.md
Labels: approved, area/build, dco-signoff: yes, kind/documentation, lgtm, size/XS

#15 Improve rendering of large output fields.
  CHANGELOG.md
  main.go
  static/index.html
Labels: approved, dco-signoff: yes, kind/design, lgtm, size/L

#17 Prevent concurrent map read/writes
  main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#19 update retention in readme
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS
