Repository falcosecurity/falcosidekick-ui, pull requests merged in 2022-06, with the labels that each got.

#51 Use Host URL as API baseURL
  frontend/.env.example
  frontend/src/http.js
  frontend/yarn.lock
Labels: kind/bug, dco-signoff: yes, lgtm, approved, size/XXL

#52 fix force redirect to localhost
  CHANGELOG.md
  docs/docs.go
  docs/swagger.json
  docs/swagger.yaml
  main.go
Labels: kind/bug, dco-signoff: yes, lgtm, approved, size/S

#55 add new TTL argument + fix settings via envvar and args
  README.md
  configuration/configuration.go
  go.mod
  go.sum
  internal/api/api.go
  internal/broadcast/broadcast.go
  internal/database/redis/client.go
  internal/database/redis/count.go
  internal/database/redis/index.go
  internal/database/redis/search.go
  internal/database/redis/set.go
  internal/events/add.go
  internal/events/count.go
  internal/events/search.go
  internal/utils/utils.go
  main.go
Labels: kind/feature, dco-signoff: yes, lgtm, approved, size/L
