Repository falcosecurity/falcosidekick-ui, pull requests merged in 2022-05, with the labels that each got.

#44 v2.0.0
  CHANGELOG.md
  Dockerfile
  Makefile
  README.md
Labels: kind/documentation, kind/feature, kind/design, dco-signoff: yes, size/M, lgtm, approved

#46 fix build-push-ecr job
  .circleci/config.yml
Labels: kind/bug, area/build, dco-signoff: yes, lgtm, approved, size/S

#47 set default since to 24h in all pages
  .goreleaser.yml
  frontend/src/components/filters.vue
  frontend/src/views/DashboardPage.vue
Labels: kind/bug, dco-signoff: yes, lgtm, approved, size/XS

#48 fix missing timelines
  frontend/src/App.vue
  frontend/src/components/charts/timeline.vue
  frontend/src/main.js
  internal/events/add.go
Labels: kind/bug, dco-signoff: yes, lgtm, approved, size/S

#49 prepare-2.0.1
  CHANGELOG.md
Labels: dco-signoff: yes, needs-kind, lgtm, approved, size/XS
