Repository falcosecurity/falcosidekick-ui, pull requests merged in 2023-01, with the labels that each got.

#77 Update the CI
  .circleci/config.yml
Labels: kind/cleanup, area/build, dco-signoff: yes, size/M, lgtm, approved

#80 add filters for the jobs in circle ci
  .circleci/config.yml
Labels: kind/bug, area/build, dco-signoff: yes, lgtm, approved, size/S

#81 update circleci config for the release job
  .circleci/config.yml
Labels: kind/cleanup, area/build, dco-signoff: yes, size/M, lgtm, approved

#82 add test-infra context in CircleCI for release
  .circleci/config.yml
Labels: kind/failing-test, area/build, dco-signoff: yes, lgtm, approved, size/XS

#83 remove auth for healthchecks
  .goreleaser.yml
  main.go
Labels: kind/bug, dco-signoff: yes, size/M, lgtm, approved
