Repository falcosecurity/falcosidekick-ui, pull requests merged in 2023-09, with the labels that each got.

#114 prepare v2.2.0
  CHANGELOG.md
Labels: kind/feature, dco-signoff: yes, lgtm, approved, size/S

#115 fix(gha): update role to assume
  .github/workflows/release.yml
Labels: kind/bug, area/build, dco-signoff: yes, lgtm, approved, size/XS

#116 fix build of arm images
  .goreleaser.yml
Labels: kind/bug, area/build, dco-signoff: yes, lgtm, approved, size/S

#117 fix typo in .goreleaser.yaml for build of docker images
  .goreleaser.yml
Labels: kind/bug, dco-signoff: yes, size/M, lgtm, approved

#118 fix(gha): update role to assume for push-main workflow
  .github/workflows/push-main.yml
Labels: kind/bug, area/build, dco-signoff: yes, lgtm, approved, size/XS

#119 add release folder
  release/ldflags.sh
Labels: kind/failing-test, dco-signoff: yes, size/M, lgtm, approved
